#!/bin/sh

#
# make the log directory
# remove the previous app.properties file
# call:  make all
#
# for now, keep Install, app.properties.default in-sync
#
# need to redo the Install to use MGICONFIG && app.properties.default
#

cd `dirname $0`
. Configuration

mkdir -p ${LOG_DIR}

PROP_FILE=app.properties
rm -f ${PROP_FILE}

echo "swarm.logging=INFO" >> ${PROP_FILE}
echo "swarm.http.port=${JAVA_API_PORT}" >> ${PROP_FILE}
echo "swarm.ds.username=${MGD_DBUSER}" >> ${PROP_FILE}
echo "swarm.ds.password=`cat ${PG_1LINE_PASSFILE}`" >> ${PROP_FILE}
echo "swarm.ds.connection.url=${MGD_JDBC_URL}" >> ${PROP_FILE}
echo "swarm.access_token=${JAVA_API_TOKEN}" >> ${PROP_FILE}
echo "swarm.ds.dbname=${MGD_DBNAME}" >> ${PROP_FILE}
echo "swarm.ds.dbpasswordfile=${PG_1LINE_PASSFILE}" >> ${PROP_FILE}
echo "swarm.ds.dbserver=${MGD_DBSERVER}" >> ${PROP_FILE}
echo "swarm.ds.eiUtilities=${PYTHON} ${PG_DBUTILS}/bin/ei/markerWithdrawal.py" >> ${PROP_FILE}
echo "swarm.ds.alleleCombinationUtilities=${PYTHON} ${DBUTILS}/allcacheload/allelecombinationByGenotype.py" >> ${PROP_FILE}
echo "swarm.ds.mrkLocationUtilities=${PYTHON} ${DBUTILS}/mrkcacheload/mrklocation.py" >> ${PROP_FILE}
echo "swarm.ds.mrkrefByMarkerUtilities=${PYTHON} ${DBUTILS}/mrkcacheload/mrkrefByMarker.py" >> ${PROP_FILE}
echo "swarm.ds.mrkrefByReferenceUtilities=${PYTHON} ${DBUTILS}/mrkcacheload/mrkrefByReference.py" >> ${PROP_FILE}
echo "swarm.ds.mrkmcvUtilities=${PYTHON} ${DBUTILS}/mrkcacheload/mrkmcv.py" >> ${PROP_FILE}
echo "swarm.ds.gorefsUtilities=${PYTHON} ${DBUTILS}/pgdbutilities/bin/ei/GORefs.py" >> ${PROP_FILE}
echo "swarm.ds.pixeldb=/data/pixeldb" >> ${PROP_FILE}
echo "swarm.ds.pixeldbCounter=/data/pixeldb/accession/counter" >> ${PROP_FILE}

make all
