#!/bin/sh

#
# make the log directory
# remove the previous app.properties file
# call:  make all
#
# for now, keep Install, app.properties.default in-sync
#
# need to redo the Install to use MGICONFIG && app.properties.default
#

cd `dirname $0`
. Configuration

mkdir -p ${LOG_DIR}

TEMPL_FILE=./application.properties.template
PROP_FILE=./src/main/resources/application.properties
cat ${TEMPL_FILE} | envsubst > ${PROP_FILE}

mvn -T 8 clean package -Dquarkus.package.type=uber-jar -ntp
