#
# for bheidev01 : must use additional network parameters
#
# -Djava.net.preferIPv4Stack=true 
# -Djava.net.preferIPv4Addresses=true
#

all:
	mvn clean package

run:
	/usr/java/jdk1.8.0_131/bin/java -jar target/mgd_java_api-swarm.jar -Papp.properties -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
