#!/bin/sh

#
# 1. echo config variables to app.properties
# 2. call:  make all
#
# *must* keep Install, app.properties.default in-sync
#
# swarm does not support env variables, so we must use 'echo'
#

cd `dirname $0`
. Configuration

#
# must cat the config values
# because maven does not like environment variables
#
mkdir -p ${LOG_DIR}
PROP_FILE=app.properties
rm -f ${PROP_FILE}
echo "swarm.logging=INFO" >> ${PROP_FILE}
echo "swarm.http.port=${JAVA_API_PORT}" >> ${PROP_FILE}
echo "swarm.ds.username=${MGD_DBUSER}" >> ${PROP_FILE}
echo "swarm.ds.password=`cat ${PG_1LINE_PASSFILE}`" >> ${PROP_FILE}
echo "swarm.ds.connection.url=${MGD_JDBC_URL}" >> ${PROP_FILE}
echo "swarm.access_token=${JAVA_API_TOKEN}" >> ${PROP_FILE}
echo "swarm.ds.dbname=${MGD_DBNAME}" >> ${PROP_FILE}
echo "swarm.ds.dbpasswordfile=${PG_1LINE_PASSFILE}" >> ${PROP_FILE}
echo "swarm.ds.dbserver=${MGD_DBSERVER}" >> ${PROP_FILE}
echo "swarm.ds.eiUtilities=${PG_DBUTILS}/bin/ei/markerWithdrawal.py" >> ${PROP_FILE}

make all
